const GENERAL_DATE_FORMAT:string = 'DD-MM-YYYY';
const GENERAL_DATETIME_FORMAT:string = 'DD-MM-YYYY HH:mm:ss';
const GENERAL_TIME_FORMAT:string = 'HH:mm:ss';
const GENERAL_DATETIME_FORMAT_SUBREGISTRATION:string = 'DD-MM-YYYY H:mm';
const GENERAL_TIME_FORMAT_WITHOUT_SECONDS:string = 'HH:mm';


export { GENERAL_DATE_FORMAT, GENERAL_DATETIME_FORMAT, GENERAL_TIME_FORMAT, GENERAL_DATETIME_FORMAT_SUBREGISTRATION, GENERAL_TIME_FORMAT_WITHOUT_SECONDS }
